// <auto-generated />
using System;
using CadastroEscolar_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroEscolar_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            cpf = "raquelsilva276@gmail.com",
                            email = "875.363.800-03",
                            nascimento = "08/09/2004",
                            nome = "Raquel Silva",
                            sexo = "feminino",
                            telefone = "55119548345"
                        },
                        new
                        {
                            id = 2,
                            cpf = "laurinhasous@gmail.com",
                            email = "875.363.800-03",
                            nascimento = "12/10/2003",
                            nome = "Laura Sousa",
                            sexo = "feminino",
                            telefone = "5511899874"
                        },
                        new
                        {
                            id = 3,
                            cpf = "rbkvitoria245@gmail.com",
                            email = "566.978.230-54",
                            nascimento = "21/05/2005",
                            nome = "Rebeka Vitória",
                            sexo = "feminino",
                            telefone = "5511986549"
                        },
                        new
                        {
                            id = 4,
                            cpf = "phenriq24@gmail.com",
                            email = "718.723.720-07",
                            nascimento = "30/04/2003",
                            nome = "Pedro Henrique",
                            sexo = "masculino",
                            telefone = "5511976548"
                        },
                        new
                        {
                            id = 5,
                            cpf = "Otvport985@gmail.com",
                            email = "141.133.870-79",
                            nascimento = "16/01/2004",
                            nome = "Otávio Porto",
                            sexo = "masculino",
                            telefone = "551154325"
                        },
                        new
                        {
                            id = 6,
                            cpf = "Juluisa57@gmail.com",
                            email = "161.781.950-60",
                            nascimento = "05/02/2002",
                            nome = "Luisa Junior",
                            sexo = "feminino",
                            telefone = "556614124"
                        },
                        new
                        {
                            id = 7,
                            cpf = "VitinhoNobrega924@gmail.com",
                            email = "778.402.420-73",
                            nascimento = "29/07/2004",
                            nome = "Vitor Nobrega",
                            sexo = "masculino",
                            telefone = "556543245"
                        });
                });

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5
                        });
                });

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Carlos"
                        },
                        new
                        {
                            id = 2,
                            nome = "Ricardo"
                        },
                        new
                        {
                            id = 3,
                            nome = "Tiago"
                        },
                        new
                        {
                            id = 4,
                            nome = "Rubens"
                        },
                        new
                        {
                            id = 5,
                            nome = "Clara"
                        },
                        new
                        {
                            id = 6,
                            nome = "Isabela"
                        },
                        new
                        {
                            id = 7,
                            nome = "Celia"
                        });
                });

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("CadastroEscolar_WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("CadastroEscolar_WebAPI.Models.Professor", null)
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("CadastroEscolar_WebAPI.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
